<!-- Instructions: This is the template you will use to type up your responses to the exercises and the on your own questions. To produce a document that you can print out and turn in just click on Knit HTML above. All you need to do to complete the lab is to type up your BRIEF answers and the R code (when necessary) in the spaces provided below. If you want to find out more about the markdown language click on the MD icon. -->

Lab 10
========================================================

#### Author: Colm Kennedy


**Load data:**

```{r}
download.file('https://mmmlab.org/courses/psych400/data/evals.RData',
              destfile='~/R/data/evals.RData')
load('data/evals.RData')
```


#### Exercise 1:



#### Exercise 2:

<!--Insert any code that should be run in the console into the block below-->
```{r}
hist(evals$score)
boxplot(evals$score)
```

#### Exercise 3:

<!--Insert any code that should be run in the console into the block below-->
```{r}
plot(jitter(evals$score)~jitter(evals$bty_avg))

```


#### Exercise 4:

<!--Insert any code that should be run in the console into the block below-->
```{r}
cor(evals$score, evals$bty_avg)
m_bty <- lm(score~bty_avg, data = evals)
summary(m_bty)


```

#### Exercise 5:

<!--Insert any code that should be run in the console into the block below-->
```{r}
plot(jitter(evals$score)~jitter(evals$bty_avg))
abline(m_bty)
```

#### Exercise 6:

<!--Insert any code that should be run in the console into the block below-->
```{r}
plot(m_bty$residuals~evals$bty_avg, main='Residual Plot')
qqnorm(m_bty$residuals)
qqline(m_bty$residuals)
```

#### Exercise 7:

<!--Insert any code that should be run in the console into the block below-->
```{r}
pairs(evals[,13:19])

m_bty_gen <- lm(score~bty_avg + gender, data =evals)
summary(m_bty_gen)
```

#### Exercise 8:



#### Exercise 9:



#### Exercise 10:

<!--Insert any code that should be run in the console into the block below-->
```{r}
multiLines(m_bty_gen)

m_bty_rank <- lm(score~bty_avg + rank,data = evals)
summary(m_bty_rank)
multiLines(m_bty_rank)
```

#### Exercise 11:

<!--Insert any code that should be run in the console into the block below-->
```{r}
m_full <- lm(score ~ rank + ethnicity + gender + language + age + cls_perc_eval 
             + cls_students + cls_level + cls_profs + cls_credits + bty_avg 
             + pic_outfit + pic_color, data = evals)
summary(m_full)

```

#### Exercise 12:

<!--Insert any code that should be run in the console into the block below-->
```{r}

```

#### Exercise 13:



#### Exercise 14:

<!--Insert any code that should be run in the console into the block below-->
```{r}
m_full_m1 <- lm(score ~ rank + ethnicity + gender + language + age + cls_perc_eval 
             + cls_students + cls_level + cls_credits + bty_avg 
             + pic_outfit + pic_color, data = evals)
##summary(m_full_m1)

m_full_m2 <- lm(score ~ rank + ethnicity + gender + language + age + cls_perc_eval 
             + cls_students + cls_credits + bty_avg 
             + pic_outfit + pic_color, data = evals)
summary(m_full_m2)

# do this until p value starts to rise, then go back
```

#### Exercise 15:

<!--Insert any code that should be run in the console into the block below-->
```{r}

```

#### Exercise 16:

<!--Insert any code that should be run in the console into the block below-->
```{r}

```

#### Exercise 17:



#### Exercise 18:



#### Exercise 19:

